name: checkout code

on: [push]

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: list
        run: |
          ls