name: simple shell commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello shell!!"
      - name: multiline script
        run: |
          echo "Hello"
          npm -v
  run-powershell-commands:
    runs-on: windows-latest
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Present Directory
        run: dir
    